// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTK7PZuOLcjhMjvObNyBDVpTmB2G3jKSM',
    appId: '1:829604596982:web:4a143ae6bcf1fde6c1b0d7',
    messagingSenderId: '829604596982',
    projectId: 'eco-guardian-roverbin-9e934',
    authDomain: 'eco-guardian-roverbin-9e934.firebaseapp.com',
    databaseURL: 'https://eco-guardian-roverbin-9e934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eco-guardian-roverbin-9e934.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5z7LGfKejwiTmmzOYB2MRSuQgmJKit8',
    appId: '1:829604596982:android:5ea24f2401eb38e7c1b0d7',
    messagingSenderId: '829604596982',
    projectId: 'eco-guardian-roverbin-9e934',
    databaseURL: 'https://eco-guardian-roverbin-9e934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eco-guardian-roverbin-9e934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSeHm4fh88_ulkg8PprbBO24349MM5ju0',
    appId: '1:829604596982:ios:7e52ecdff73f217fc1b0d7',
    messagingSenderId: '829604596982',
    projectId: 'eco-guardian-roverbin-9e934',
    databaseURL: 'https://eco-guardian-roverbin-9e934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eco-guardian-roverbin-9e934.appspot.com',
    iosClientId: '829604596982-ei0vgbfg41l5oqfqmv5hnkmlvlihnde6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoGuardianRoverbinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSeHm4fh88_ulkg8PprbBO24349MM5ju0',
    appId: '1:829604596982:ios:733aade49c3f08d3c1b0d7',
    messagingSenderId: '829604596982',
    projectId: 'eco-guardian-roverbin-9e934',
    databaseURL: 'https://eco-guardian-roverbin-9e934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eco-guardian-roverbin-9e934.appspot.com',
    iosClientId: '829604596982-immdvl48gkf0h9oh01540473gn7th57i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoGuardianRoverbinApp.RunnerTests',
  );
}
